runtime: go120
includes:
  - gcp_appengine_data/appeng-environment.yaml
instance_class: f1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 0.030s
  max_instances: 1
